version: '3.8'

services:
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    networks:
      - app-network
  
  frontend:
    build:
      context: ../Frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:5173"  
    depends_on:
      - backend
      - mssql-db
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network  

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-db,1433;Database=YourDatabaseName;User Id=sa;Password=YourStrongPassword!;Encrypt=False
    ports:
      - "5000:8080"
    depends_on:
      - mssql-db
      - migrate
    networks:
      - app-network
  
  migrate:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /app
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.dotnet/tools
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql-db,1433;Database=YourDatabaseName;User Id=sa;Password=YourStrongPassword!;Encrypt=False
    command: >      
      sh -c "dotnet tool install --global dotnet-ef && dotnet restore && dotnet ef database update"
    volumes:
      - .:/app
    depends_on:
      - mssql-db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
